### ISSUE TITLE
Switch to using wl-paste --watch mode

### ISSUE THREAD

**Issue by bugaevc** [sentriz/cliphist-sh#1]
Just as https://github.com/janza/wl-clipboard-history/issues/5, please check out https://github.com/bugaevc/wl-clipboard/issues/39#issuecomment-528948344 and https://github.com/bugaevc/wl-clipboard/issues/59 and https://github.com/yory8/clipman/issues/1 and switch to using `wl-paste --watch` instead of polling!

**Comment by sentriz** [comment]
oooh very cool man thank you for finding this and letting me know :)
I am wondering is it possible to watch for changes on both clipboards at once? or would that be silly?
If not I can do something like
```
wl-paste --watch <cmd> & 
wl-paste --primary --watch <cmd> & 
```

**Comment by bugaevc** [comment]
> oooh very cool man thank you for finding this and letting me know :)

😀

> I am wondering is it possible to watch for changes on both clipboards at once? or would that be silly?

Not at the moment, but I definitely consider this for a future extension. Yeah, you should just use two instances for now.

**Comment by sentriz** [comment]
sounds good to me. i'll be trying this out very soon

**Comment by sentriz** [comment]
done :D

the code is not good but it was tricky to keep clipboards in sync, and whether they end with newlines or not. wanted to keep vim linewise vs characterwise right for example
